# Generated by Django 6.0.1 on 2026-02-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=255)),
                ('main_price', models.FloatField()),
                ('red_price', models.FloatField()),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('memory', models.CharField(blank=True, max_length=50, null=True)),
                ('producer', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_diagonal', models.CharField(blank=True, max_length=50, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.TextField()),
                ('review_count', models.IntegerField(default=0)),
                ('characteristics', models.JSONField(default=dict)),
            ],
        ),
    ]
